alias ll="ls -lah"
alias cd..="cd .."
alias bitcoin-cli="bitcoin-cli -datadir=${BITCOIN_DATADIR}"
alias btclog="multitail --retry -cS btclog -f ${BITCOIN_DATADIR}/debug.log"
alias btcup="bitcoind -datadir=${BITCOIN_DATADIR}"
alias btcdown="bitcoin-cli stop"
alias cronlog="grep CRON /var/log/syslog"
alias cls="clear"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
